import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useIntl } from 'react-intl';
import { getAllowedReasoningLevels, RUNTIME_POLICY_CEILINGS } from '@herobids/domain';
import { agents as agentsApi, capabilities as capabilitiesApi, connections as connectionsApi, auth as authApi, ai as aiApi, providerCatalog as providerCatalogApi, dashboard, type AgentOutcomes, type Skill } from '../../lib/api-client.js';
import { PageShell, PageHeader, LoadingRows, ErrorState, Button, Card, MetricCard, FieldLabel, ErrorBanner, inputStyle } from '../../lib/ui.js';
import { BlueprintBrowse } from '../blueprints/BlueprintBrowse.js';
import { BlueprintInstantiateFlow } from '../blueprints/BlueprintInstantiateFlow.js';
import type { BlueprintSummary } from '../../lib/api-client.js';
import { formatExecutionMode, formatSkillSelection, hasCapabilityFamily, resolveSkillPresetSkillIds, resolvePromptTemplate, resolveGoalPlaceholder, resolveGoalPlaceholderKey, type SkillPresetId } from './agent-display.js';
import { AgentSummaryCard } from './AgentSummaryCard.js';
import { SkillPicker } from './SkillPicker.js';
import { localizeApiError } from '../../lib/localize-api-error.js';
import { formatPnl, pnlColor } from '../../lib/formatting.js';
import { useEventStream, type UserEvent } from '../../lib/useEventStream.js';
import { ProviderSetupForm } from '../setup/ProviderSetupForm.js';
import { ModelSelectionFields, resolveDefaultModelSelection } from '../settings/ModelSelectionFields.js';
import { resolveCreateAgentModelPayload } from './create-agent-models.js';
import { buildCreateAgentPayload, resolveCreateAgentConnectionIds } from './agent-payloads.js';
import { TradingGuardrailsFields } from './AgentControlsSection.js';
import { getTickIntervalValidationMessageId, parseTickIntervalMinutesInput } from './tick-interval.js';
import { type CapabilityMode, type HybridMode } from './CapabilitySelector.js';
import { applyAutoMaxHoldOverride, type AgentStyleValue, resolveStyleDefaults, formatStyleSummary, resolveModelPricing, type RuntimePolicyOverrides } from './style-mapping.js';

const STYLE_LABEL_KEYS: Record<AgentStyleValue, string> = {
  careful: 'agents.style.careful.label',
  balanced: 'agents.style.balanced.label',
  bold: 'agents.style.bold.label',
};
import { generateAgentName } from './agent-name.js';
import { PromptInputBlock } from './PromptInputBlock.js';
import { AgentFormBody } from './AgentFormBody.js';
import { intentToFormState } from './agent-form-state.js';
import { defaultTechnicalConfigFormState, technicalFormStateToPayload, type TechnicalConfigFormState } from './technical-config-helpers.js';
import { validateCreateAgentForm, type ValidationConstraints } from './form-validation.js';
import { RuntimePolicySection } from './RuntimePolicySection.js';


import { VENUE_TYPE_MAP, buildVenueTypeMap } from './venue-mapping.js';

type CreateStep = 'intent' | 'review';

interface IntentState {
  name: string;
  goal: string;
  capabilityMode: CapabilityMode;
  hybridMode?: HybridMode;
  /** true = technical pre-filter scanner runs before LLM decides (ON by default for trading agents) */
  technicalPreFilterEnabled: boolean;
  technicalConfig: TechnicalConfigFormState;
  skillPreset: SkillPresetId;
  skillIds: string[];
  /** Authorization mode: 'direct' | 'approval_required'. Default depends on preset. */
  authorizationMode: 'direct' | 'approval_required';
  executionMode: 'test' | 'live';
  provider: string;
  lightModel: string;
  heavyModel: string;
  telegramChatId: string;
  connectionIds: string[];
  /** Per-agent email delivery override. */
  emailDelivery: 'inherit' | 'allow' | 'disable';
  /** Derived from selected connection's provider, or user-picked in test mode. */
  venue: string;
  /** Derived from venue: hyperliquid→orderbook, jupiter→swap, etc. */
  venueType: '' | 'orderbook' | 'swap';
  style: AgentStyleValue;
  // Configurable controls
  costPreset: '' | 'minimal' | 'standard' | 'premium' | 'custom';
  dailySpendBudgetUsd: string;
  tickIntervalMins: string;
  capital: string;
  dailyMaxLossPct: string;
  maxDrawdownPct: string;
  maxSlippageBps: string;
  maxOpenPositions: string;
  maxPositionSizePct: string;
  stopLossPct: string;
  stopLossCooldownSecs: string;
  openPositionEscalationToJudgePolicy: 'never' | 'uncovered_or_triggered' | 'always';
  runtimePolicyOverrides: RuntimePolicyOverrides | null;
  strategyPreset: string;
  platformAssessmentEnabled: boolean;
  platformAssessmentReviewIntervalHours: string;
  subscribedSources: string[];
  pendingFiles: File[];
}

type CreateAgentOAuthDraft = {
  step: CreateStep;
  intent: Omit<IntentState, 'pendingFiles'>;
  nameIsAutoGenerated: boolean;
  dailyLossLimitAuto: boolean;
  maxHoldDurationManuallySet: boolean;
  policyManuallySet: boolean;
};

const CREATE_AGENT_OAUTH_DRAFT_KEY = 'create-agent-oauth-draft-v1';

function saveCreateAgentOAuthDraft(draft: CreateAgentOAuthDraft): void {
  try {
    window.sessionStorage.setItem(CREATE_AGENT_OAUTH_DRAFT_KEY, JSON.stringify(draft));
  } catch {
    // Ignore storage failures; OAuth return will still fall back to reopening the form.
  }
}

function loadCreateAgentOAuthDraft(): CreateAgentOAuthDraft | null {
  try {
    const raw = window.sessionStorage.getItem(CREATE_AGENT_OAUTH_DRAFT_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as CreateAgentOAuthDraft;
    if (!parsed || typeof parsed !== 'object' || !parsed.intent) return null;
    return parsed;
  } catch {
    return null;
  }
}

function clearCreateAgentOAuthDraft(): void {
  try {
    window.sessionStorage.removeItem(CREATE_AGENT_OAUTH_DRAFT_KEY);
  } catch {
    // Ignore storage failures.
  }
}

export function AgentsPage() {
  const [agentTab, setAgentTab] = useState<'my-agents' | 'marketplace'>('my-agents');
  const [selectedBlueprint, setSelectedBlueprint] = useState<BlueprintSummary | null>(null);
  const intl = useIntl();
  const navigate = useNavigate();
  const qc = useQueryClient();

  const query = useQuery({
    queryKey: ['agents'],
    queryFn: () => agentsApi.list(),
  });

  const outcomesQuery = useQuery({
    queryKey: ['agents', 'outcomes'],
    queryFn: () => agentsApi.outcomes(),
  });

  const outcomesByAgentId = useMemo(() => {
    const map = new Map<string, AgentOutcomes['outcomes']>();
    for (const entry of outcomesQuery.data?.outcomes ?? []) {
      map.set(entry.agentId, entry.outcomes);
    }
    return map;
  }, [outcomesQuery.data]);

  // ── Dashboard data (from Mission Control) ──────────────────────
  const handleEvent = useCallback((event: UserEvent) => {
    if (event.type === 'agent.status') {
      void qc.invalidateQueries({ queryKey: ['agents'] });
    }
  }, [qc]);
  useEventStream(handleEvent);

  const overviewQuery = useQuery({
    queryKey: ['dashboard', 'overview'],
    queryFn: () => dashboard.overview(),
  });

  const items = query.data ?? [];

  // New users (0 agents) are sent straight to guided chat so they
  // can build their first agent without an empty list in the way.
  useEffect(() => {
    if (query.isSuccess && items.length === 0) {
      navigate('/agents/new?ui=chat', { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query.isSuccess, items.length]);

  const activeCount = items.filter((agent) => agent.status === 'active' || agent.status === 'starting').length;

  return (
    <PageShell>
      <PageHeader
        title={intl.formatMessage({ id: 'agents.title' })}
        action={
          <Button variant="primary" size="sm" onClick={() => navigate('/agents/new')}>
            {intl.formatMessage({ id: 'agents.create.title' })}
          </Button>
        }
      />

      {/* ── Tab bar ─────────────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: '4px', marginBottom: '20px' }}>
        <Button
          variant={agentTab === 'my-agents' ? 'primary' : 'secondary'}
          size="sm"
          onClick={() => setAgentTab('my-agents')}
        >
          My Agents
        </Button>
        <Button
          variant={agentTab === 'marketplace' ? 'primary' : 'secondary'}
          size="sm"
          onClick={() => setAgentTab('marketplace')}
        >
          Marketplace
        </Button>
      </div>

      {/* ── My Agents tab ───────────────────────────────────────── */}
      {agentTab === 'my-agents' && (
        <>
          {query.isLoading && <LoadingRows count={3} />}
          {query.isError && <ErrorState message={localizeApiError(intl, query.error, 'common.errorTitle')} onRetry={() => void query.refetch()} />}

          <div className="agents-content">
          {/* ── Summary metrics ─────────────────────────────────────── */}
          {query.isSuccess && items.length > 0 && (
            <div className="metrics-summary-row">
              <MetricCard className="metrics-summary-card" label={intl.formatMessage({ id: 'missionControl.metric.active' })} value={activeCount} total={items.length} />
              <MetricCard
                className="metrics-summary-card"
                label={intl.formatMessage({ id: 'missionControl.metric.totalPnl' })}
                value={overviewQuery.isLoading ? '—' : formatPnl(overviewQuery.data?.summary.outcomes.trading?.totalRealizedPnl)}
                color={overviewQuery.isLoading ? undefined : pnlColor(overviewQuery.data?.summary.outcomes.trading?.totalRealizedPnl)}
              />
            </div>
          )}

          {query.isSuccess && items.length > 0 && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {items.map((agent) => (
                <AgentSummaryCard key={agent.id} agent={agent} outcomes={outcomesByAgentId.get(agent.id)} />
              ))}
            </div>
          )}
          </div>
        </>
      )}

      {/* ── Marketplace tab ──────────────────────────────────────── */}
      {agentTab === 'marketplace' && (
        <BlueprintBrowse
          defaultKind="agent"
          hideKindFilter
          onUseBlueprint={setSelectedBlueprint}
        />
      )}

      {/* ── Blueprint instantiate flow ────────────────────────────── */}
      {selectedBlueprint && (
        <BlueprintInstantiateFlow
          blueprint={selectedBlueprint}
          onClose={() => setSelectedBlueprint(null)}
          onCreated={(actorId) => {
            setSelectedBlueprint(null);
            setAgentTab('my-agents');
            void qc.invalidateQueries({ queryKey: ['agents'] });
            navigate(`/agents/${actorId}`);
          }}
        />
      )}

    </PageShell>
  );
}

export function CreateAgentFlow({
  skills,
  skillsLoading,
  skillsError,
  onClose,
  onCreated,
}: {
  skills: Skill[];
  skillsLoading: boolean;
  skillsError: string | null;
  onClose: () => void;
  onCreated: (id: string) => void;
}) {
  const intl = useIntl();
  const qc = useQueryClient();
  const location = useLocation();
  const navigate = useNavigate();
  const [step, setStep] = useState<CreateStep>('intent');
  const [showSetup, setShowSetup] = useState(false);
  const [intent, setIntent] = useState<IntentState>(() => {
    const styleDefaults = resolveStyleDefaults('balanced');
    return {
    name: '',
    goal: '',
    capabilityMode: 'intelligence',
    hybridMode: undefined,
    technicalPreFilterEnabled: false,
    technicalConfig: defaultTechnicalConfigFormState(),
    skillPreset: 'trading',
    skillIds: resolveSkillPresetSkillIds('trading'),
    authorizationMode: 'direct',
    executionMode: 'test',
    provider: '',
    lightModel: '',
    heavyModel: '',
    telegramChatId: '',
    connectionIds: [],
    emailDelivery: 'inherit' as const,
    venue: '',
    venueType: '',
    style: 'balanced',
    costPreset: styleDefaults.costPreset,
    dailySpendBudgetUsd: styleDefaults.dailySpendBudgetUsd,
    tickIntervalMins: styleDefaults.tickIntervalMins,
    capital: '',
    dailyMaxLossPct: '',
    maxDrawdownPct: '',
    maxSlippageBps: '',
    maxOpenPositions: '',
    maxPositionSizePct: '',
    stopLossPct: '',
    stopLossCooldownSecs: '',
    openPositionEscalationToJudgePolicy: styleDefaults.openPositionEscalationToJudgePolicy,
    runtimePolicyOverrides: null,
    strategyPreset: '',
    platformAssessmentEnabled: false,
    platformAssessmentReviewIntervalHours: '24',
    subscribedSources: ['watch_threshold', 'discovery_delta', 'regime_change'],
    pendingFiles: [],
    };
  });
  const [modelTouched, setModelTouched] = useState(false);
  const [telegramTouched, setTelegramTouched] = useState(false);
  const [reasoningTouched, setReasoningTouched] = useState(false);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [nameIsAutoGenerated, setNameIsAutoGenerated] = useState(true);
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [skillsExpanded, setSkillsExpanded] = useState(false);
  const dailyMaxLossPctAutoRef = useRef(false);
  const maxHoldDurationManuallySetRef = useRef(false);
  // Phase 7 policy dropdown onChange will set this to true.
  const policyManuallySetRef = useRef(false);
  const handledOauthReturnRef = useRef(false);

  function resolveTickIntervalMsFromMinutesInput(tickIntervalMins: string): number | null {
    const parsed = parseTickIntervalMinutesInput(tickIntervalMins);
    return parsed.kind === 'valid' ? parsed.tickIntervalMs : null;
  }

  const meQuery = useQuery({
    queryKey: ['me'],
    queryFn: () => authApi.me(),
  });
  const aiSettingsQuery = useQuery({
    queryKey: ['ai', 'settings'],
    queryFn: () => aiApi.settings(),
  });
  const availableModelsQuery = useQuery({
    queryKey: ['ai', 'available-models'],
    queryFn: () => aiApi.availableModels(),
  });

  useEffect(() => {
    if (handledOauthReturnRef.current) return;

    const params = new URLSearchParams(location.search);
    if (params.get('oauthReturn') !== '1') return;

    handledOauthReturnRef.current = true;
    const restoredDraft = loadCreateAgentOAuthDraft();
    const connectionId = params.get('connectionId');
    const status = params.get('status');

    if (restoredDraft) {
      setStep(restoredDraft.step);
      setIntent((prev) => ({
        ...prev,
        ...restoredDraft.intent,
        connectionIds: connectionId
          ? Array.from(new Set([...(restoredDraft.intent.connectionIds ?? []), connectionId]))
          : restoredDraft.intent.connectionIds,
        pendingFiles: [],
      }));
      setNameIsAutoGenerated(restoredDraft.nameIsAutoGenerated);
      dailyLossLimitAutoRef.current = restoredDraft.dailyLossLimitAuto;
      maxHoldDurationManuallySetRef.current = restoredDraft.maxHoldDurationManuallySet;
      policyManuallySetRef.current = restoredDraft.policyManuallySet;
    }

    if (status === 'ok') {
      void qc.invalidateQueries({ queryKey: ['connections'] });
      void qc.invalidateQueries({ queryKey: ['capabilities', 'trading', 'connections'] });
    }

    clearCreateAgentOAuthDraft();

    params.delete('oauthReturn');
    params.delete('setup');
    params.delete('status');
    params.delete('error');
    params.delete('connectionId');
    const nextSearch = params.toString();
    navigate(nextSearch ? `/agents?${nextSearch}` : '/agents', { replace: true });
  }, [location.search, navigate, qc]);
  const tradingConnectionsQuery = useQuery({
    queryKey: ['capabilities', 'trading', 'connections'],
    queryFn: () => capabilitiesApi.tradingConnections(),
  });
  const allConnectionsQuery = useQuery({
    queryKey: ['connections'],
    queryFn: () => connectionsApi.list(),
  });
  const riskDefaultsQuery = useQuery({
    queryKey: ['agents', 'risk-defaults'],
    queryFn: () => agentsApi.riskDefaults(),
  });
  const providerCatalogQuery = useQuery({
    queryKey: ['providerCatalog'],
    queryFn: () => providerCatalogApi.get(),
    staleTime: 60 * 60 * 1000, // 1 hour — providers rarely change
  });

  const venueTypeMap = providerCatalogQuery.data?.providers
    ? buildVenueTypeMap(providerCatalogQuery.data.providers)
    : VENUE_TYPE_MAP;

  useEffect(() => {
    if (modelTouched) {
      return;
    }
    const savedModels = aiSettingsQuery.data?.aiModelConfig;
    if (savedModels) {
      setIntent((state) => ({
        ...state,
        provider: savedModels.provider ?? '',
        lightModel: savedModels.lightModel ?? '',
        heavyModel: savedModels.heavyModel ?? '',
      }));
    }
  }, [aiSettingsQuery.data?.aiModelConfig, modelTouched]);

  useEffect(() => {
    if (modelTouched) {
      return;
    }
    if (intent.provider) {
      return;
    }
    if (!aiSettingsQuery.isSuccess || aiSettingsQuery.data?.aiModelConfig) {
      return;
    }
    const defaultSelection = resolveDefaultModelSelection(availableModelsQuery.data?.providers ?? [], availableModelsQuery.data?.defaults);
    if (!defaultSelection) {
      return;
    }
    setIntent((state) => ({ ...state, ...defaultSelection }));
  }, [availableModelsQuery.data?.providers, aiSettingsQuery.isSuccess, aiSettingsQuery.data?.aiModelConfig, intent.provider, modelTouched]);

  // Auto-fill reasoning levels from saved AI settings when first loaded
  useEffect(() => {
    if (reasoningTouched) return;
    const savedModels = aiSettingsQuery.data?.aiModelConfig;
    if (!savedModels) return;
    setIntent((state) => {
      // Only auto-fill if the user hasn't already set reasoning overrides
      const existingOverrides = state.runtimePolicyOverrides ?? {};
      if (existingOverrides.scoutReasoning != null && existingOverrides.judgeReasoning != null) return state;
      return {
        ...state,
        runtimePolicyOverrides: {
          ...state.runtimePolicyOverrides,
          ...(existingOverrides.scoutReasoning == null && savedModels.scoutReasoning ? { scoutReasoning: savedModels.scoutReasoning } : {}),
          ...(existingOverrides.judgeReasoning == null && savedModels.judgeReasoning ? { judgeReasoning: savedModels.judgeReasoning } : {}),
        },
      };
    });
  }, [aiSettingsQuery.data?.aiModelConfig, reasoningTouched]);

  useEffect(() => {
    if (telegramTouched) {
      return;
    }
    const chatId = meQuery.data?.telegramChatId;
    if (chatId !== undefined) {
      setIntent((state) => ({ ...state, telegramChatId: chatId ?? '' }));
    }
  }, [meQuery.data?.telegramChatId, telegramTouched]);

  // Sync capabilityMode from technicalPreFilterEnabled toggle + trading skill presence
  useEffect(() => {
    setIntent((state) => {
      const resolvedSkills = skills.filter((s) => state.skillIds.includes(s.id));
      const syntheticTradingSkill = (state.skillPreset === 'trading' || state.skillPreset === 'direct-trading' || state.skillPreset === 'trading-assistant')
        ? [{ capabilityFamilies: ['trading'] }]
        : [];
      const effectiveSkills = resolvedSkills.length > 0 ? resolvedSkills : syntheticTradingSkill;
      const hasTradingSkill = hasCapabilityFamily(effectiveSkills, 'trading');
      const derived: CapabilityMode = state.technicalPreFilterEnabled && hasTradingSkill ? 'hybrid' : 'intelligence';
      if (derived !== state.capabilityMode) {
        return { ...state, capabilityMode: derived };
      }
      return state;
    });
  }, [intent.skillIds, intent.technicalPreFilterEnabled, skills]);

  // Pre-fill goal from promptTemplate when skills change and goal is empty
  useEffect(() => {
    if (intent.goal.trim()) return;
    const template = resolvePromptTemplate(intent.skillIds, skills);
    if (template) {
      setIntent((state) => ({ ...state, goal: template }));
    }
  }, [intent.skillIds, skills]);

  // Auto-generate name from style when nameIsAutoGenerated is true
  useEffect(() => {
    if (nameIsAutoGenerated) {
      const newName = generateAgentName(intent.style);
      setIntent((state) => ({ ...state, name: newName }));
    }
  }, [intent.style, nameIsAutoGenerated]);

  // Auto-fill dailyMaxLossPct from operator default percentage when capital is set
  useEffect(() => {
    if (dailyMaxLossPctAutoRef.current || !intent.dailyMaxLossPct.trim()) {
      const capitalNum = parseFloat(intent.capital);
      if (!isNaN(capitalNum) && capitalNum > 0) {
        const defaultPct = riskDefaultsQuery.data?.dailyMaxLossPct;
        if (defaultPct != null && String(defaultPct) !== intent.dailyMaxLossPct) {
          setIntent((state) => ({ ...state, dailyMaxLossPct: String(defaultPct) }));
          dailyMaxLossPctAutoRef.current = true;
        }
      }
    }
  }, [intent.capital, riskDefaultsQuery.data?.dailyMaxLossPct]);

  const selectedSkills = skills.filter((skill) => intent.skillIds.includes(skill.id));
  const hasBotManagementSkill = intent.skillIds.includes('bot-management');
  const tickIntervalValidationMessageId = getTickIntervalValidationMessageId(intent.tickIntervalMins);
  const tickIntervalError = tickIntervalValidationMessageId
    ? intl.formatMessage({ id: tickIntervalValidationMessageId })
    : null;
  const savedModelSettings = aiSettingsQuery.data?.aiModelConfig ?? null;
  const modelPayload = resolveCreateAgentModelPayload(
    { provider: intent.provider, lightModel: intent.lightModel, heavyModel: intent.heavyModel },
    savedModelSettings,
  );
  const showIntelligence = intent.capabilityMode === 'intelligence' || intent.capabilityMode === 'hybrid';
  const requiresTradingSetup = intent.skillPreset === 'trading' || intent.skillPreset === 'direct-trading' || intent.skillPreset === 'trading-assistant' || hasCapabilityFamily(selectedSkills, 'trading');
  const availableConnections = (tradingConnectionsQuery.data?.connections ?? []).filter(
    (connection) => connection.status === 'active',
  );
  // Generic connections (all providers including Gmail) for the picker display
  const genericConnections = (allConnectionsQuery.data?.connections ?? []).filter(
    (c) => c.status === 'active',
  );
  // Build a merged view for the connection picker. Prefer trading-connection
  // entries when available (they carry richer data), but include generic entries
  // for non-trading providers like Gmail.
  const allPickerConnections = useMemo(() => {
    const seen = new Set<string>();
    const merged: Array<{ connectionId: string; provider: string; label: string; status: string; profile?: Record<string, unknown> | null }> = [];
    // Add trading connections first (they have priority for trading display)
    for (const c of availableConnections) {
      if (!seen.has(c.connectionId)) {
        seen.add(c.connectionId);
        merged.push({ connectionId: c.connectionId, provider: c.provider, label: c.label, status: c.connectionStatus, profile: c.profile });
      }
    }
    // Add generic connections not already covered
    for (const c of genericConnections) {
      if (!seen.has(c.id)) {
        seen.add(c.id);
        merged.push({ connectionId: c.id, provider: c.provider, label: c.label, status: c.status, profile: c.profile });
      }
    }
    return merged;
  }, [availableConnections, genericConnections]);

  // Auto-select connection when skills change (6.4)
  const prevSkillIdsRef = useRef<string[]>(intent.skillIds);
  useEffect(() => {
    if (!allConnectionsQuery.isSuccess && !tradingConnectionsQuery.isSuccess) return;
    const prevSkillIds = prevSkillIdsRef.current;
    prevSkillIdsRef.current = intent.skillIds;

    setIntent((state) => {
      // Don't override existing selections
      if (state.connectionIds.length > 0) return state;

      const hasEmailSkill = state.skillIds.includes('email');
      const hasTradingSkill = state.skillIds.includes('trading') || state.skillIds.includes('bot-management');
      const newlyAddedEmail = hasEmailSkill && !prevSkillIds.includes('email');
      const newlyAddedTrading = hasTradingSkill && !prevSkillIds.some((id) => id === 'trading' || id === 'bot-management');

      if (newlyAddedEmail) {
        const emailConn = allPickerConnections.find((c) => c.provider === 'gmail');
        if (emailConn) {
          return { ...state, connectionIds: [emailConn.connectionId] };
        }
      }

      if (newlyAddedTrading) {
        const tradingConns = allPickerConnections.filter((c) => venueTypeMap[c.provider] !== undefined);
        if (tradingConns.length === 1) {
          return { ...state, connectionIds: [tradingConns[0]!.connectionId] };
        }
      }

      return state;
    });
  }, [intent.skillIds, allConnectionsQuery.isSuccess, tradingConnectionsQuery.isSuccess, allPickerConnections]);

  // In test mode show all venues (the user may optionally pick one to enable
  // venue-backed shadow execution, but none is required). In live mode only
  // show venues that have at least one active connection.
  const venuesForMode = intent.executionMode === 'test'
    ? Object.keys(venueTypeMap).sort()
    : Object.keys(venueTypeMap).filter((v) => availableConnections.some((c) => c.provider === v)).sort();

  // When connections finish loading and a venue is already set with no connection chosen,
  // auto-select if exactly one connection matches the venue.
  useEffect(() => {
    if (!tradingConnectionsQuery.isSuccess) return;
    setIntent((state) => {
      if (!state.venue || state.connectionIds.length > 0) return state;
      const matching = (tradingConnectionsQuery.data?.connections ?? [])
        .filter((c) => c.status === 'active' && c.provider === state.venue);
      if (matching.length === 1) {
        return { ...state, connectionIds: [matching[0]!.connectionId] };
      }
      return state;
    });
  }, [tradingConnectionsQuery.isSuccess, tradingConnectionsQuery.data]);

  const mutation = useMutation({
    mutationFn: async () => {
      // When a strategy preset is selected, don't send raw technical config
      const hasStrategyPreset = intent.strategyPreset && intent.strategyPreset !== 'custom';
      const technicalPayload = (!hasStrategyPreset && intent.technicalPreFilterEnabled && requiresTradingSetup)
        ? technicalFormStateToPayload(intent.technicalConfig, intent.venue, intent.venueType as 'orderbook' | 'swap')
        : null;
      const agent = await agentsApi.create(buildCreateAgentPayload({
        name: intent.name,
        goal: intent.goal,
        capabilityMode: intent.capabilityMode,
        hybridMode: intent.hybridMode ?? 'scanner_gated',
        technicalPreFilterEnabled: intent.technicalPreFilterEnabled,
        technical: technicalPayload,
        skillIds: intent.skillIds,
        hasBotManagementSkill,
        requiresTradingSetup,
        executionMode: intent.executionMode,
        executionVenue: intent.venue,
        connectionIds: intent.connectionIds,
        modelPayload,
        costPreset: intent.costPreset,
        dailySpendBudgetUsd: intent.dailySpendBudgetUsd,
        telegramChatId: intent.telegramChatId,
        emailDelivery: intent.emailDelivery,
        tickIntervalMins: intent.tickIntervalMins,
        capital: intent.capital,
        dailyMaxLossPct: intent.dailyMaxLossPct,
        maxDrawdownPct: intent.maxDrawdownPct,
        maxSlippageBps: intent.maxSlippageBps,
        maxOpenPositions: intent.maxOpenPositions,
        maxPositionSizePct: intent.maxPositionSizePct,
        stopLossPct: intent.stopLossPct,
        stopLossCooldownSecs: intent.stopLossCooldownSecs,
        style: intent.style,
        strategyPreset: intent.strategyPreset || undefined,
        openPositionEscalationToJudgePolicy: intent.openPositionEscalationToJudgePolicy,
        runtimePolicyOverrides: intent.runtimePolicyOverrides ?? undefined,
        subscribedSources: intent.subscribedSources,
        platformAssessmentEnabled: intent.platformAssessmentEnabled,
        platformAssessmentReviewIntervalHours: intent.platformAssessmentReviewIntervalHours,
        skillPresetId: intent.skillPreset !== 'custom' ? intent.skillPreset : undefined,
        authorizationMode: intent.authorizationMode,
      }));

      // Upload any documents selected during creation
      if (intent.pendingFiles && intent.pendingFiles.length > 0) {
        for (const file of intent.pendingFiles) {
          try {
            await agentsApi.uploadDocument(agent.id, file);
          } catch (err) {
            console.warn('Document upload failed:', file.name, err);
          }
        }
      }

      return agent;
    },
    onSuccess: (agent) => onCreated(agent.id),
    onError: () => {
      setFormErrors((prev) => ({ ...prev, _form: localizeApiError(intl, mutation.error, 'common.errorTitle') }));
    },
  });

  function clearFieldError(field: string) {
    setFormErrors((prev) => {
      if (!(field in prev)) return prev;
      const next = { ...prev };
      delete next[field];
      return next;
    });
  }

  const validationConstraints: ValidationConstraints = {
    maxOpenPositions: riskDefaultsQuery.data?.maxOpenPositions ?? 10,
    maxPositionSizePct: riskDefaultsQuery.data?.maxPositionSizePct ?? 100,
    stopLossPct: riskDefaultsQuery.data?.stopLossPct ?? 100,
  };

  function validateFieldOnBlur(fieldName: string) {
    const result = validateCreateAgentForm({
      name: intent.name,
      goal: intent.goal,
      capabilityMode: intent.capabilityMode,
      capital: intent.capital,
      tickIntervalMins: intent.tickIntervalMins,
      maxOpenPositions: intent.maxOpenPositions,
      maxPositionSizePct: intent.maxPositionSizePct,
      stopLossPct: intent.stopLossPct,
      venue: intent.venue,
      venueType: intent.venueType,
      executionMode: intent.executionMode,
      requiresTradingSetup,
      hasConnection: intent.connectionIds.length > 0,
      style: intent.style,
      runtimePolicyOverrides: intent.runtimePolicyOverrides,
    }, validationConstraints);

    setFormErrors((prev) => {
      const fieldError = result.errors[fieldName];
      const hasExisting = fieldName in prev;
      if (!fieldError && !hasExisting) return prev;
      const next = { ...prev };
      if (fieldError) {
        next[fieldName] = fieldError;
      } else {
        delete next[fieldName];
      }
      return next;
    });

  }

  const maxHoldViolation = (() => {
    if (!intent.tickIntervalMins.trim() || tickIntervalError != null) return false;
    const tickNum = Number(intent.tickIntervalMins);
    if (!Number.isFinite(tickNum) || tickNum < 1 || !Number.isInteger(tickNum)) return false;
    const tickMs = tickNum * 60_000;
    const maxHoldMs = intent.runtimePolicyOverrides?.maxHoldDurationMs;
    return maxHoldMs != null && maxHoldMs !== 0 && maxHoldMs < tickMs;
  })();

  const createDisabled = mutation.isPending
    || !intent.name.trim()
    || (intent.executionMode === 'live' && (!intent.venue || !intent.venueType))
    || (requiresTradingSetup && intent.venue.trim() !== '' && intent.connectionIds.length === 0)
    || tickIntervalError != null
    || maxHoldViolation;

  if (showSetup) {
    return (
      <ProviderSetupForm
        defaultCapability="trading"
        oauthReturnTo="/agents?create=1&oauthReturn=1"
        onBeforeOAuthRedirect={() => {
          const { pendingFiles: _pendingFiles, ...serializableIntent } = intent;
          saveCreateAgentOAuthDraft({
            step,
            intent: serializableIntent,
            nameIsAutoGenerated,
            dailyLossLimitAuto: dailyLossLimitAutoRef.current,
            maxHoldDurationManuallySet: maxHoldDurationManuallySetRef.current,
            policyManuallySet: policyManuallySetRef.current,
          });
        }}
        onClose={() => setShowSetup(false)}
        onSuccess={(result) => {
          setShowSetup(false);
          void qc.invalidateQueries({ queryKey: ['capabilities', 'trading', 'connections'] });
          const connectionIds = resolveCreateAgentConnectionIds(result.connection ?? null);
          if (connectionIds.length > 0) {
            setIntent((state) => ({ ...state, connectionIds: [...new Set([...state.connectionIds, ...connectionIds])] }));
          }
        }}
      />
    );
  }

  if (step === 'intent') {
    return (
      <div className="create-flow-card">
        <div className="create-flow-card-header">
          <span>{intl.formatMessage({ id: 'agents.create.title' })}</span>
          <button type="button" onClick={onClose} aria-label="Close" className="create-flow-card-close">✕</button>
        </div>
        <div className="create-flow-card-body" style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>

          {/* 1. Skill Preset — first, sets context for everything else */}
          <div style={{ marginBottom: '20px' }}>
            <FieldLabel>{intl.formatMessage({ id: 'agents.create.skillPreset' })}</FieldLabel>
            <select
              value={intent.skillPreset}
              onChange={(e) => {
                const skillPreset = e.target.value as SkillPresetId;
                setIntent((state) => {
                  const next = {
                    ...state,
                    skillPreset,
                    skillIds: resolveSkillPresetSkillIds(skillPreset, state.skillIds),
                    // authorizationMode defaults to direct for all presets
                    authorizationMode: 'direct' as const,
                  };
                  // Clear trading sessions when switching away from trading
                  // so the hour grid (0-23) becomes editable again.
                  if (skillPreset !== 'trading' && next.runtimePolicyOverrides?.tradingSessions) {
                    const { tradingSessions: _, ...rest } = next.runtimePolicyOverrides;
                    next.runtimePolicyOverrides = Object.keys(rest).length > 0 ? rest : null;
                  }
                  return next;
                });
              }}
              style={{ ...inputStyle, cursor: 'pointer' }}
            >
              <option value="trading">{intl.formatMessage({ id: 'agents.create.skillPreset.trading' })}</option>
              <option value="personal-assistant">{intl.formatMessage({ id: 'agents.create.skillPreset.personalAssistant' })}</option>
              <option value="custom">{intl.formatMessage({ id: 'agents.create.skillPreset.custom' })}</option>
            </select>
            {intent.skillPreset !== 'custom' && selectedSkills.length > 0 && (
              <div style={{ marginTop: '4px', fontSize: '0.75rem', color: 'var(--color-text-muted)', lineHeight: '1.4' }}>
                {selectedSkills.map((s) => s.name).join(', ')}
              </div>
            )}
          </div>

          {/* Skills section — always collapsed, expandable */}
          <div style={{ marginBottom: '20px' }}>
            <button
              type="button"
              onClick={() => setSkillsExpanded((prev) => !prev)}
              style={{
                background: 'none',
                border: 'none',
                padding: 0,
                cursor: 'pointer',
                fontSize: '0.875rem',
                fontWeight: '600',
                color: 'var(--color-text)',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
              }}
            >
              <span style={{ transform: skillsExpanded ? 'rotate(90deg)' : 'rotate(0deg)', transition: 'transform 0.15s', display: 'inline-block' }}>▸</span>
              {intent.skillPreset === 'custom'
                ? intl.formatMessage({ id: 'agents.create.skills.addLabel', defaultMessage: 'Add skills' })
                : intl.formatMessage({ id: 'agents.create.skills.editLabel', defaultMessage: 'Edit skills' })}
              <span className="optional-hint">
                {intl.formatMessage({ id: 'common.optional', defaultMessage: '(Optional)' })}
              </span>
            </button>
            {skillsExpanded && (
              <div style={{ marginTop: '12px' }}>
                <SkillPicker
                  skills={skills}
                  selectedSkillIds={intent.skillIds}
                  onChange={(skillIds) => setIntent((state) => ({ ...state, skillIds }))}
                  loading={skillsLoading}
                  errorMessage={skillsError}
                />
              </div>
            )}
          </div>

          {/* 2. Prompt + files + style — unified block */}
          <div style={{ marginBottom: '8px' }}>
          <PromptInputBlock
            dataField="goal"
            goal={intent.goal}
            onGoalChange={(goal) => {
              clearFieldError('goal');
              setIntent((state) => ({ ...state, goal }));
            }}
            onGoalBlur={() => validateFieldOnBlur('goal')}
            goalPlaceholder={intl.formatMessage({ id: resolveGoalPlaceholderKey(intent.skillPreset) })}
            goalLabel={<>{intl.formatMessage({ id: intent.capabilityMode === 'hybrid' ? 'agents.create.goalBoth' : 'agents.create.goal' })}{' '}<span className="goal-subtitle">{intl.formatMessage({ id: intent.capabilityMode === 'hybrid' ? 'agents.create.goalBoth.subtitle' : 'agents.create.goal.subtitle' })}</span></>}
            goalError={formErrors.goal}
            pendingFiles={intent.pendingFiles}
            onPendingFilesChange={(pendingFiles) => setIntent((state) => ({ ...state, pendingFiles }))}
            style={intent.style}
            onStyleChange={(style) => {
              const defaults = resolveStyleDefaults(style);
              setIntent((state) => {
                const tradingSources = ['watch_threshold', 'discovery_delta', 'regime_change'];
                const styleSources = state.technicalPreFilterEnabled
                  ? [...tradingSources, 'scanner']
                  : tradingSources;
                const next: IntentState = {
                  ...state,
                  style,
                  costPreset: defaults.costPreset,
                  tickIntervalMins: defaults.tickIntervalMins,
                  dailySpendBudgetUsd: defaults.dailySpendBudgetUsd,
                  subscribedSources: styleSources,
                  ...(policyManuallySetRef.current ? {} : { openPositionEscalationToJudgePolicy: defaults.openPositionEscalationToJudgePolicy }),
                };
                const newTickMs = resolveTickIntervalMsFromMinutesInput(next.tickIntervalMins);
                const effectiveMaxHold = next.runtimePolicyOverrides?.maxHoldDurationMs
                  ?? resolveStyleDefaults(style).maxHoldDurationMs;
                const constraintViolated = newTickMs != null && effectiveMaxHold !== 0 && effectiveMaxHold < newTickMs;
                return maxHoldDurationManuallySetRef.current && !constraintViolated
                  ? next
                  : {
                      ...next,
                      runtimePolicyOverrides: applyAutoMaxHoldOverride(
                        style,
                        next.runtimePolicyOverrides,
                        newTickMs,
                      ),
                    };
              });
            }}
          />

          {/* Style summary */}
          <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', marginTop: '0' }}>
            {formatStyleSummary(intent.style, intl.formatMessage({ id: STYLE_LABEL_KEYS[intent.style] }), resolveModelPricing(
              availableModelsQuery.data?.providers ?? [],
              intent.provider,
              intent.lightModel,
              intent.heavyModel,
            ), resolveTickIntervalMsFromMinutesInput(intent.tickIntervalMins))}
          </div>

          </div>

          {/* 3. Agent Form Body */}
          <AgentFormBody
            value={intentToFormState(intent)}
            onChange={(patch) => {
              if ('name' in patch) setNameIsAutoGenerated(false);
              setIntent((state) => {
                const next: IntentState = { ...state, ...patch };
                if (patch.tickIntervalMins !== undefined) {
                  const newTickMs = resolveTickIntervalMsFromMinutesInput(next.tickIntervalMins);
                  const effectiveMaxHold = next.runtimePolicyOverrides?.maxHoldDurationMs
                    ?? resolveStyleDefaults(next.style).maxHoldDurationMs;
                  const constraintViolated = newTickMs != null && effectiveMaxHold !== 0 && effectiveMaxHold < newTickMs;
                  if (!maxHoldDurationManuallySetRef.current || constraintViolated) {
                    next.runtimePolicyOverrides = applyAutoMaxHoldOverride(
                      next.style,
                      next.runtimePolicyOverrides,
                      newTickMs,
                    );
                  }
                }
                return next;
              });
            }}
            showIntelligence={showIntelligence}
            showTradingControls={requiresTradingSetup}
            requiresTradingSetup={requiresTradingSetup}
            isAdmin={meQuery.data?.isAdmin ?? false}
            agentStyle={intent.style}
            accountEmail={meQuery.data?.email ?? null}
            selectableSkills={skills}
            skillsLoading={skillsLoading}
            skillsError={skillsError}
            formErrors={formErrors}
            onClearFieldError={clearFieldError}
            onBlurField={validateFieldOnBlur}
            validationConstraints={validationConstraints}
            tickIntervalError={tickIntervalError}
            subscribedSources={intent.subscribedSources}
            onSubscribedSourcesChange={(sources) => setIntent((state) => ({ ...state, subscribedSources: sources }))}
            computeBudgetSlot={
              <RuntimePolicySection
                style={intent.style}
                overrides={intent.runtimePolicyOverrides}
                onChange={(overrides) => {
                  const hasManualMaxHoldOverride = Object.prototype.hasOwnProperty.call(overrides ?? {}, 'maxHoldDurationMs');
                  maxHoldDurationManuallySetRef.current = hasManualMaxHoldOverride;
                  if (hasManualMaxHoldOverride) {
                    clearFieldError('tickIntervalMins');
                  }
                  setIntent((state) => ({
                    ...state,
                    runtimePolicyOverrides: hasManualMaxHoldOverride
                      ? overrides
                      : applyAutoMaxHoldOverride(
                          state.style,
                          overrides,
                          resolveTickIntervalMsFromMinutesInput(state.tickIntervalMins),
                        ),
                  }));
                }}
                alwaysExpanded
                showTradingSessionPresets={requiresTradingSetup}
              />
            }
            modelSlot={
              showIntelligence ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <div style={{ fontSize: '0.875rem', fontWeight: '600' }}>
                    {intl.formatMessage({ id: 'agents.create.models.title' })}
                  </div>
                  <ModelSelectionFields
                    value={{ provider: intent.provider, lightModel: intent.lightModel, heavyModel: intent.heavyModel }}
                    providers={availableModelsQuery.data?.providers ?? []}
                    loading={availableModelsQuery.isLoading}
                    loadingLabel={intl.formatMessage({ id: 'aiModels.loading' })}
                    emptyLabel={intl.formatMessage({ id: 'aiModels.empty' })}
                    providerLabel={intl.formatMessage({ id: 'aiModels.provider.label' })}
                    providerPlaceholder={intl.formatMessage({ id: 'aiModels.provider.placeholder' })}
                    economyLabel={intl.formatMessage({ id: 'aiModels.economy.label' })}
                    economyHelp={intl.formatMessage({ id: 'aiModels.economy.help' })}
                    premiumLabel={intl.formatMessage({ id: 'aiModels.premium.label' })}
                    premiumHelp={intl.formatMessage({ id: 'aiModels.premium.help' })}
                    onChange={(value) => {
                      setModelTouched(true);
                      setIntent((state) => ({ ...state, ...value }));
                    }}
                  />

                  {/* Reasoning level dropdowns */}
                  {(() => {
                    const savedReasoning = aiSettingsQuery.data?.aiModelConfig;
                    const overrides = intent.runtimePolicyOverrides ?? {};
                    const scoutVal = (overrides.scoutReasoning as string | null) ?? null;
                    const judgeVal = (overrides.judgeReasoning as string | null) ?? null;
                    const inheritedScout = savedReasoning?.scoutReasoning ?? 'none';
                    const inheritedJudge = savedReasoning?.judgeReasoning ?? 'medium';

                    return (
                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                        <div>
                          <FieldLabel>{intl.formatMessage({ id: 'agents.edit.models.reasoning.scoutLabel' })}</FieldLabel>
                          <select
                            aria-label={intl.formatMessage({ id: 'agents.edit.models.reasoning.scoutLabel' })}
                            value={scoutVal ?? ''}
                            onChange={(e) => {
                              setReasoningTouched(true);
                              const val = e.target.value;
                              setIntent((state) => {
                                const next = { ...(state.runtimePolicyOverrides ?? {}) };
                                if (val === '' || val === null) {
                                  delete next.scoutReasoning;
                                } else {
                                  next.scoutReasoning = val;
                                }
                                return {
                                  ...state,
                                  runtimePolicyOverrides: Object.keys(next).length > 0 ? next as RuntimePolicyOverrides : null,
                                };
                              });
                            }}
                            style={{ ...inputStyle, cursor: 'pointer', width: '100%' }}
                          >
                            <option value="">
                              {intl.formatMessage({ id: 'agents.edit.models.reasoning.inherit' }, { value: inheritedScout })}
                            </option>
                            {getAllowedReasoningLevels(RUNTIME_POLICY_CEILINGS.scoutReasoningMax).map((level) => (
                              <option key={level} value={level}>{intl.formatMessage({ id: `aiModels.reasoning.${level}` })}</option>
                            ))}
                          </select>
                          <div style={{ marginTop: '6px', fontSize: '0.75rem', color: 'var(--color-text-muted)', lineHeight: '1.5' }}>
                            {intl.formatMessage({ id: 'agents.edit.models.reasoning.scoutHelp' })}
                          </div>
                        </div>
                        <div>
                          <FieldLabel>{intl.formatMessage({ id: 'agents.edit.models.reasoning.judgeLabel' })}</FieldLabel>
                          <select
                            aria-label={intl.formatMessage({ id: 'agents.edit.models.reasoning.judgeLabel' })}
                            value={judgeVal ?? ''}
                            onChange={(e) => {
                              setReasoningTouched(true);
                              const val = e.target.value;
                              setIntent((state) => {
                                const next = { ...(state.runtimePolicyOverrides ?? {}) };
                                if (val === '' || val === null) {
                                  delete next.judgeReasoning;
                                } else {
                                  next.judgeReasoning = val;
                                }
                                return {
                                  ...state,
                                  runtimePolicyOverrides: Object.keys(next).length > 0 ? next as RuntimePolicyOverrides : null,
                                };
                              });
                            }}
                            style={{ ...inputStyle, cursor: 'pointer', width: '100%' }}
                          >
                            <option value="">
                              {intl.formatMessage({ id: 'agents.edit.models.reasoning.inherit' }, { value: inheritedJudge })}
                            </option>
                            <option value="none">{intl.formatMessage({ id: 'aiModels.reasoning.none' })}</option>
                            <option value="low">{intl.formatMessage({ id: 'aiModels.reasoning.low' })}</option>
                            <option value="medium">{intl.formatMessage({ id: 'aiModels.reasoning.medium' })}</option>
                            <option value="high">{intl.formatMessage({ id: 'aiModels.reasoning.high' })}</option>
                          </select>
                          <div style={{ marginTop: '6px', fontSize: '0.75rem', color: 'var(--color-text-muted)', lineHeight: '1.5' }}>
                            {intl.formatMessage({ id: 'agents.edit.models.reasoning.judgeHelp' })}
                          </div>
                        </div>
                      </div>
                    );
                  })()}
                </div>
              ) : null
            }
            connectionSlot={
              <div data-field="connectionIds" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                <FieldLabel>{intl.formatMessage({ id: 'agents.create.connections' })}{' '}<span className="optional-hint">{intl.formatMessage({ id: 'common.optional', defaultMessage: '(Optional)' })}</span></FieldLabel>
                {(tradingConnectionsQuery.isLoading || allConnectionsQuery.isLoading) ? (
                  <div style={{ fontSize: '0.8125rem', color: 'var(--color-text-muted)' }}>{intl.formatMessage({ id: 'agents.create.loadingConnections' })}</div>
                ) : allPickerConnections.length === 0 ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', lineHeight: '1.5' }}>
                      {intl.formatMessage({ id: 'agents.create.noConnections' })}
                    </div>
                    <div>
                      <Button variant="secondary" size="sm" onClick={() => setShowSetup(true)}>
                        {intl.formatMessage({ id: 'agents.create.addConnection' })}
                      </Button>
                    </div>
                  </div>
                ) : (
                  <>
                    <select
                      value=""
                      onChange={(e) => {
                        const id = e.target.value;
                        if (!id) return;
                        const conn = allPickerConnections.find((c) => c.connectionId === id);
                        const provider = conn?.provider ?? '';
                        const isTradingProvider = venueTypeMap[provider] !== undefined;
                        const derivedVenue = isTradingProvider ? provider : '';
                        const derivedVenueType = isTradingProvider ? (venueTypeMap[provider] ?? '') : '';
                        if (isTradingProvider) clearFieldError('venue');
                        setIntent((state) => {
                          let newIds: string[];
                          if (isTradingProvider) {
                            // For trading connections: filter to same-provider trading + keep all non-trading
                            newIds = state.connectionIds.filter((cid) => {
                              const pc = allPickerConnections.find((c) => c.connectionId === cid);
                              if (!pc) return true;
                              const isTrading = venueTypeMap[pc.provider] !== undefined;
                              return !isTrading || pc.provider === provider;
                            });
                            if (!newIds.includes(id)) newIds = [...newIds, id];
                          } else {
                            // Non-trading connections: always allow accumulation
                            newIds = state.connectionIds.includes(id)
                              ? state.connectionIds
                              : [...state.connectionIds, id];
                          }
                          return {
                            ...state,
                            connectionIds: newIds,
                            ...(isTradingProvider ? { venue: derivedVenue, venueType: derivedVenueType } : {}),
                          };
                        });
                      }}
                      style={{ ...inputStyle, cursor: 'pointer' }}
                    >
                      <option value="">{intl.formatMessage({ id: 'agents.create.chooseConnection' })}</option>
                      {/* Trading connections group */}
                      {allPickerConnections.some((c) => venueTypeMap[c.provider] !== undefined) && (
                        <optgroup label={intl.formatMessage({ id: 'agents.create.connections.trading' })}>
                          {allPickerConnections
                            .filter((c) => venueTypeMap[c.provider] !== undefined)
                            .map((connection) => (
                              <option key={connection.connectionId} value={connection.connectionId}>
                                {connection.label} ({connection.provider})
                              </option>
                            ))}
                        </optgroup>
                      )}
                      {/* Non-trading connections group (e.g. Gmail) */}
                      {allPickerConnections.some((c) => venueTypeMap[c.provider] === undefined) && (
                        <optgroup label={intl.formatMessage({ id: 'agents.create.connections.other' })}>
                          {allPickerConnections
                            .filter((c) => venueTypeMap[c.provider] === undefined)
                            .map((connection) => (
                              <option key={connection.connectionId} value={connection.connectionId}>
                                {connection.label} ({connection.provider})
                              </option>
                            ))}
                        </optgroup>
                      )}
                    </select>
                    {intent.connectionIds.length > 0 && (
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                        {intent.connectionIds.map((id) => {
                          const conn = allPickerConnections.find((c) => c.connectionId === id);
                          return (
                            <span
                              key={id}
                              style={{
                                display: 'inline-flex',
                                alignItems: 'center',
                                gap: '4px',
                                padding: '2px 8px',
                                borderRadius: '12px',
                                background: 'var(--color-surface-2)',
                                fontSize: '0.75rem',
                                cursor: 'default',
                              }}
                            >
                              {conn?.label ?? id}
                              <button
                                type="button"
                                onClick={() => setIntent((state) => {
                                  const newIds = state.connectionIds.filter((cid) => cid !== id);
                                  const removedConn = allPickerConnections.find((c) => c.connectionId === id);
                                  const isTradingConn = removedConn && venueTypeMap[removedConn.provider] !== undefined;
                                  // Clear venue when the last trading connection is removed
                                  const remainingTrading = newIds.some((cid) => {
                                    const c = allPickerConnections.find((pc) => pc.connectionId === cid);
                                    return c && venueTypeMap[c.provider] !== undefined;
                                  });
                                  return {
                                    ...state,
                                    connectionIds: newIds,
                                    ...(isTradingConn && !remainingTrading && requiresTradingSetup
                                      ? { venue: '', venueType: '' }
                                      : {}),
                                  };
                                })}
                                style={{
                                  background: 'none',
                                  border: 'none',
                                  cursor: 'pointer',
                                  padding: '0 2px',
                                  fontSize: '0.875rem',
                                  lineHeight: '1',
                                  color: 'var(--color-text-muted)',
                                }}
                              >
                                ×
                              </button>
                            </span>
                          );
                        })}
                      </div>
                    )}
                  </>
                )}
                {allPickerConnections.length > 0 && (
                  <button
                    type="button"
                    onClick={() => setShowSetup(true)}
                    style={{
                      background: 'none',
                      border: 'none',
                      cursor: 'pointer',
                      padding: '4px 0',
                      fontSize: '0.75rem',
                      color: 'var(--color-brand)',
                      textAlign: 'left',
                    }}
                  >
                    {intl.formatMessage({ id: 'agents.create.addConnection' })}
                  </button>
                )}

                {formErrors.connectionIds && (
                  <div style={{ color: 'var(--color-danger)', fontSize: '0.75rem' }}>{formErrors.connectionIds}</div>
                )}
              </div>
            }
            tradingSetupSlot={
              requiresTradingSetup ? (
                <>
                  <div data-field="executionMode">
                    <FieldLabel>{intl.formatMessage({ id: 'agents.executionMode.label' })}</FieldLabel>
                    <select
                      value={intent.executionMode}
                      onChange={(e) => {
                        const newMode = e.target.value as IntentState['executionMode'];
                        clearFieldError('executionMode');
                        setIntent((state) => {
                          // In live mode, venue must have an active connection;
                          // in test mode, keep any venue selection.
                          const venueStillValid = newMode === 'test' ||
                            !state.venue ||
                            availableConnections.some((c) => c.provider === state.venue);
                          return {
                            ...state,
                            executionMode: newMode,
                            ...(venueStillValid ? {} : { venue: '', venueType: '', connectionIds: [] }),
                          };
                        });
                      }}
                      style={{ ...inputStyle, cursor: 'pointer' }}
                    >
                      <option value="test">{intl.formatMessage({ id: 'agents.create.executionMode.test' })}</option>
                      <option value="live">{intl.formatMessage({ id: 'agents.create.executionMode.live' })}</option>
                    </select>
                    {formErrors.executionMode && (
                      <div style={{ color: 'var(--color-danger)', fontSize: '0.75rem', marginTop: '4px' }}>
                        {formErrors.executionMode}
                      </div>
                    )}
                  </div>

                  {/* Venue — user picks market first; connection list filters to match */}
                  <div data-field="venue">
                    <FieldLabel>{intl.formatMessage({ id: 'agents.technical.filters.venue' })}</FieldLabel>
                    <select
                      value={intent.venue}
                      onChange={(e) => {
                        const v = e.target.value;
                        const vt = venueTypeMap[v] ?? '';
                        clearFieldError('venue');
                        clearFieldError('executionMode');
                        setIntent((state) => {
                          const matching = availableConnections.filter((c) => c.provider === v);
                          // Auto-select if exactly one match; keep matched existing selections
                          // if multiple; clear only when no connections match the new venue.
                          const newConnectionIds = matching.length === 1
                            ? [matching[0]!.connectionId]
                            : matching.length === 0
                              ? []
                              : state.connectionIds.filter((id) => matching.some((m) => m.connectionId === id));
                          return { ...state, venue: v, venueType: vt, connectionIds: newConnectionIds };
                        });
                      }}
                      style={{ ...inputStyle, cursor: 'pointer' }}
                    >
                      <option value="">{intl.formatMessage({ id: 'agents.technical.filters.venue.placeholder' })}</option>
                      {venuesForMode.map((v) => (
                        <option key={v} value={v}>{v}</option>
                      ))}
                    </select>
                    {formErrors.venue && <div style={{ color: 'var(--color-danger)', fontSize: '0.75rem', marginTop: '4px' }}>{formErrors.venue}</div>}
                  </div>

                  {/* Trade Authorization */}
                  <div data-field="authorizationMode">
                    <FieldLabel>{intl.formatMessage({ id: 'agents.authorizationMode.label' })}</FieldLabel>
                    <select
                      style={{ ...inputStyle, cursor: 'pointer' }}
                      value={intent.authorizationMode}
                      onChange={(e) => setIntent((prev) => ({ ...prev, authorizationMode: e.target.value as 'direct' | 'approval_required' }))}
                    >
                      <option value="direct">{intl.formatMessage({ id: 'agents.authorizationMode.direct' })}</option>
                      <option value="approval_required">{intl.formatMessage({ id: 'agents.authorizationMode.approvalRequired' })}</option>
                    </select>
                    <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', marginTop: '4px' }}>
                      {intent.authorizationMode === 'direct'
                        ? intl.formatMessage({ id: 'agents.authorizationMode.directHelp' })
                        : intl.formatMessage({ id: 'agents.authorizationMode.approvalRequiredHelp' })}
                    </div>
                  </div>

                  <div>
                    <div style={{ fontSize: '0.875rem', fontWeight: '600', marginBottom: '12px' }}>
                      {intl.formatMessage({ id: 'agents.create.tradingControls.title' })}
                    </div>
                    <TradingGuardrailsFields
                      value={{
                        dailyMaxLossPct: intent.dailyMaxLossPct,
                        maxDrawdownPct: intent.maxDrawdownPct,
                        maxSlippageBps: intent.maxSlippageBps,
                        maxOpenPositions: intent.maxOpenPositions,
                        maxPositionSizePct: intent.maxPositionSizePct,
                        stopLossPct: intent.stopLossPct,
                        stopLossCooldownSecs: intent.stopLossCooldownSecs,
                        openPositionEscalationToJudgePolicy: intent.openPositionEscalationToJudgePolicy,
                      }}
                      defaults={riskDefaultsQuery.data ?? null}
                      fieldErrors={formErrors}
                      onClearFieldError={clearFieldError}
                      onBlurField={validateFieldOnBlur}
                      onChange={(patch) => {
                        if ('dailyMaxLossPct' in patch) {
                          dailyMaxLossPctAutoRef.current = false;
                        }
                        if ('openPositionEscalationToJudgePolicy' in patch) {
                          policyManuallySetRef.current = true;
                        }
                        setIntent((state) => ({ ...state, ...patch }));
                      }}
                    />
                  </div>
                </>
              ) : null
            }

            advancedActionsSlot={
              <>
                <Button variant="ghost" onClick={onClose} type="button">{intl.formatMessage({ id: 'common.cancel' })}</Button>
                <Button
                  variant="primary"
                  type="button"
                  onClick={() => {
                    const result = validateCreateAgentForm({
                      name: intent.name,
                      goal: intent.goal,
                      capabilityMode: intent.capabilityMode,
                      capital: intent.capital,
                      tickIntervalMins: intent.tickIntervalMins,
                      maxOpenPositions: intent.maxOpenPositions,
                      maxPositionSizePct: intent.maxPositionSizePct,
                      stopLossPct: intent.stopLossPct,
                      venue: intent.venue,
                      venueType: intent.venueType,
                      executionMode: intent.executionMode,
                      requiresTradingSetup,
                      hasConnection: intent.connectionIds.length > 0,
                    }, validationConstraints);

                    if (!result.valid) {
                      setFormErrors(result.errors);
                      const firstErrorField = Object.keys(result.errors)[0];
                      if (firstErrorField) {
                        const el = document.querySelector(`[data-field="${firstErrorField}"]`);
                        el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
                      }
                      return;
                    }

                    setFormErrors({});
                    setStep('review');
                  }}
                >
                  {intl.formatMessage({ id: 'agents.create.review' })}
                </Button>
              </>
            }
            onAdvancedToggle={setAdvancedOpen}
          />

          {/* Cancel + Review buttons */}
          {advancedOpen && (
            <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
            <Button variant="ghost" onClick={onClose} type="button">{intl.formatMessage({ id: 'common.cancel' })}</Button>
            <Button
              variant="primary"
              type="button"
              onClick={() => {
                const result = validateCreateAgentForm({
                  name: intent.name,
                  goal: intent.goal,
                  capabilityMode: intent.capabilityMode,
                  capital: intent.capital,
                  tickIntervalMins: intent.tickIntervalMins,
                  maxOpenPositions: intent.maxOpenPositions,
                  maxPositionSizePct: intent.maxPositionSizePct,
                  stopLossPct: intent.stopLossPct,
                  venue: intent.venue,
                  venueType: intent.venueType,
                  executionMode: intent.executionMode,
                  requiresTradingSetup,
                  hasConnection: intent.connectionIds.length > 0,
                }, validationConstraints);

                if (!result.valid) {
                  setFormErrors(result.errors);
                  const firstErrorField = Object.keys(result.errors)[0];
                  if (firstErrorField) {
                    const el = document.querySelector(`[data-field="${firstErrorField}"]`);
                    el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
                  }
                  return;
                }

                setFormErrors({});
                setStep('review');
              }}
            >
              {intl.formatMessage({ id: 'agents.create.review' })}
            </Button>
          </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="create-flow-card">
      <div className="create-flow-card-header">
        <span>{intl.formatMessage({ id: 'agents.review.title' })}</span>
        <button type="button" onClick={onClose} aria-label="Close" className="create-flow-card-close">✕</button>
      </div>
      <div className="create-flow-card-body" style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8125rem' }}>
          <tbody>
            <ReviewRow label={intl.formatMessage({ id: 'agents.create.name' })} value={intent.name.trim()} />
            <ReviewRow
              label={intl.formatMessage({ id: 'agents.review.style' })}
              value={intl.formatMessage({ id: `agents.style.${intent.style}.label` })}
            />
            <ReviewRow
              label={intl.formatMessage({ id: 'agents.review.capabilityMode' })}
              value={intl.formatMessage({ id: intent.capabilityMode === 'hybrid'
                ? (intent.hybridMode === 'scanner_gated'
                  ? 'agents.capability.hybrid.scannerGated.label'
                  : 'agents.capability.hybrid.mixed.label')
                : `agents.capability.${intent.capabilityMode}.label` })}
            />
          </tbody>
        </table>

        {showIntelligence && intent.goal.trim() && (
          <div style={{ padding: '12px', background: 'var(--color-bg-subtle, rgba(0,0,0,0.04))', borderRadius: '6px', fontSize: '0.875rem', lineHeight: '1.5' }}>
            {intent.goal}
          </div>
        )}

        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8125rem' }}>
          <tbody>
            {requiresTradingSetup && <ReviewRow label={intl.formatMessage({ id: 'agents.executionMode.label' })} value={formatExecutionMode(intent.executionMode, intl)} />}
            {showIntelligence && (
              <ReviewRow
                label={intl.formatMessage({ id: 'agents.review.models' })}
                value={modelPayload.inherits
                  ? intl.formatMessage({ id: 'agents.review.models.inherit' })
                  : intent.provider
                  ? intl.formatMessage(
                    { id: 'agents.review.models.value' },
                    { provider: intent.provider, lightModel: intent.lightModel || intl.formatMessage({ id: 'common.default' }), heavyModel: intent.heavyModel || intl.formatMessage({ id: 'common.default' }) },
                  )
                  : intl.formatMessage({ id: 'agents.review.models.inherit' })}
              />
            )}
            {showIntelligence && (() => {
              const overrides = intent.runtimePolicyOverrides ?? {};
              const scoutReasoning = (overrides.scoutReasoning as string | undefined) ?? (aiSettingsQuery.data?.aiModelConfig?.scoutReasoning ?? 'none');
              const judgeReasoning = (overrides.judgeReasoning as string | undefined) ?? (aiSettingsQuery.data?.aiModelConfig?.judgeReasoning ?? 'medium');
              const scoutLabel = intl.formatMessage({ id: `aiModels.reasoning.${scoutReasoning}` });
              const judgeLabel = intl.formatMessage({ id: `aiModels.reasoning.${judgeReasoning}` });
              const isOverridden = (overrides.scoutReasoning != null || overrides.judgeReasoning != null);
              return (
                <ReviewRow
                  label={intl.formatMessage({ id: 'agents.edit.models.reasoning.scoutLabel' })}
                  value={isOverridden ? `${scoutLabel} / ${judgeLabel}` : intl.formatMessage({ id: 'agents.review.models.inherit' })}
                />
              );
            })()}
            {showIntelligence && <ReviewRow label={intl.formatMessage({ id: 'agents.create.skills' })} value={formatSkillSelection(selectedSkills, intl)} />}
            {requiresTradingSetup && intent.venue && <ReviewRow label={intl.formatMessage({ id: 'agents.technical.filters.venue' })} value={intent.venue} />}
            {intent.pendingFiles.length > 0 && (
              <ReviewRow
                label="Documents"
                value={intent.pendingFiles.map((file) => `${file.name} (${(file.size / 1024).toFixed(0)} KB)`).join(', ')}
              />
            )}
            {intent.strategyPreset && intent.strategyPreset !== 'custom' && (
              <ReviewRow label="Strategy preset" value={intent.strategyPreset} />
            )}
            {!intent.strategyPreset && intent.technicalPreFilterEnabled && (
              <ReviewRow
                label={intl.formatMessage({ id: 'agents.technical.scan.signalBias' })}
                value={intl.formatMessage({ id: `agents.technical.scan.signalBias.${intent.technicalConfig.signalBias === 'trend-following' ? 'trendFollowing' : 'meanReverting'}` })}
              />
            )}
            {!intent.strategyPreset && intent.technicalPreFilterEnabled && <ReviewRow label={intl.formatMessage({ id: 'agents.technical.scan.candleInterval' })} value={`${intent.technicalConfig.candles.interval} / ${intent.technicalConfig.candles.limit}`} />}
            {!intent.strategyPreset && intent.technicalPreFilterEnabled && <ReviewRow label={intl.formatMessage({ id: 'agents.technical.scan.interval' })} value={intent.technicalConfig.scanIntervalMins} />}
            <ReviewRow
              label={intl.formatMessage({ id: 'agents.review.capabilitySetup' })}
              value={requiresTradingSetup
                ? (intent.connectionIds.length > 0
                  ? intl.formatMessage({ id: 'agents.review.capabilitySetup.bound' })
                  : intl.formatMessage({ id: 'agents.review.capabilitySetup.defer' }))
                : intl.formatMessage({ id: 'agents.review.capabilitySetup.none' })}
            />
            {requiresTradingSetup && intent.connectionIds.length > 0 && (
              <ReviewRow
                label={intl.formatMessage({ id: 'agents.create.connection' })}
                value={intent.connectionIds
                  .map((id) => {
                    const conn = allPickerConnections.find((c) => c.connectionId === id);
                    return conn ? `${conn.label} (${conn.provider})` : id;
                  })
                  .join(', ')}
              />
            )}
            {/* Show non-trading connections (e.g. Gmail) even without trading setup */}
            {!requiresTradingSetup && intent.connectionIds.length > 0 && (
              <ReviewRow
                label={intl.formatMessage({ id: 'agents.create.connection' })}
                value={intent.connectionIds
                  .map((id) => {
                    const conn = allPickerConnections.find((c) => c.connectionId === id);
                    return conn ? `${conn.label} (${conn.provider})` : id;
                  })
                  .join(', ')}
              />
            )}
            {requiresTradingSetup && (
              <ReviewRow
                label={intl.formatMessage({ id: 'agents.review.openPositionEscalationPolicy' })}
                value={intl.formatMessage({ id: `agents.controls.openPositionEscalationPolicy.${intent.openPositionEscalationToJudgePolicy}` })}
              />
            )}
          </tbody>
        </table>

        {mutation.isError && <ErrorBanner message={localizeApiError(intl, mutation.error, 'common.errorTitle')} />}

        <div style={{ display: 'flex', gap: '8px', justifyContent: 'space-between' }}>
          <Button variant="ghost" onClick={() => { setStep('intent'); setFormErrors({}); mutation.reset(); }} type="button">{intl.formatMessage({ id: 'common.back' })}</Button>
          <div style={{ display: 'flex', gap: '8px' }}>
            <Button variant="ghost" onClick={onClose} type="button">{intl.formatMessage({ id: 'common.cancel' })}</Button>
            <Button
              variant="primary"
              type="button"
              disabled={createDisabled}
              onClick={() => {
                if (createDisabled) {
                  return;
                }
                mutation.mutate();
              }}
            >
              {mutation.isPending ? intl.formatMessage({ id: 'agents.create.creating' }) : intl.formatMessage({ id: 'agents.createAgent' })}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function ReviewRow({ label, value }: { label: string; value: string }) {
  return (
    <tr>
      <td style={{ padding: '6px 0', color: 'var(--color-text-muted)', whiteSpace: 'nowrap', paddingRight: '16px' }}>{label}</td>
      <td style={{ padding: '6px 0', fontWeight: '500' }}>{value}</td>
    </tr>
  );
}


