// Committed dev-signed descriptor source (Phase 3 T4.2, Decision 5).
//
// Serves the COMMITTED, dev-signed descriptor wrapper
// (`config/external-backends/<backendId>.descriptor.json`) to the generic trust
// pipeline. It replaces the deleted T3.3 ephemeral in-process stub: trust no
// longer comes from a runtime key splice — it comes from the committed public key
// in `config/default.yaml → externalBackends.<id>.trustedDescriptorSigningKeys`,
// which verifies this wrapper's signature.
//
// The wrapper is generated by `scripts/ts/generate-dev-descriptor.ts`; the private
// key is gitignored and never shipped. This source only READS the committed JSON.
//
// Lives in the config dir so the agent container (which copies `/app/config`) can
// read it by a stable repo-relative path — no new env var, consistent with how
// `config/*.yaml` is loaded (apps/worker/src/config.ts `MONOREPO_CONFIG_DIR`).
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DescriptorWrapperSchema, type DescriptorWrapper } from '@herobids/domain/external-backend';
import type { SyncDescriptorSource } from './apply-tool-visibility.js';

/** Resolve the monorepo `config/` dir the same way the worker config loader does:
 *  prefer HEROBIDS_CONFIG_DIR (set in the deploy images), else module-relative so
 *  it resolves from both `src/` (dev) and `dist/` (container) execution. */
function resolveConfigDir(): string {
  const configDir = process.env['HEROBIDS_CONFIG_DIR'];
  if (configDir !== undefined && configDir !== '') return resolve(configDir, 'config');
  const moduleDir = dirname(fileURLToPath(import.meta.url));
  // src: apps/worker/src/external-backend → ../../../../config ; dist mirrors depth.
  return resolve(moduleDir, '../../../../config');
}

/** Repo-relative path of a backend's committed descriptor wrapper JSON. */
export function descriptorFilePath(backendId: string): string {
  return resolve(resolveConfigDir(), 'external-backends', `${backendId}.descriptor.json`);
}

export interface FileDescriptorSourceLogger {
  warn(fields: Record<string, unknown>, message: string): void;
}

/**
 * Build a synchronous descriptor source over the committed wrapper file. The file
 * is read + validated ONCE at construction and cached; a missing or invalid file
 * yields a source that returns `undefined` (→ instruction-only degrade, DT3) and
 * logs once. The source only answers for the backendId the wrapper is bound to.
 */
export function createFileDescriptorSource(input: {
  backendId: string;
  logger: FileDescriptorSourceLogger;
}): SyncDescriptorSource {
  const { backendId, logger } = input;
  const path = descriptorFilePath(backendId);

  let wrapper: DescriptorWrapper | undefined;
  try {
    const parsed = DescriptorWrapperSchema.safeParse(JSON.parse(readFileSync(path, 'utf8')));
    if (parsed.success) {
      wrapper = parsed.data;
    } else {
      const issues = parsed.error.issues.map((issue) => ({ code: issue.code, path: issue.path.join('.') }));
      logger.warn({ backendId, issues }, 'File descriptor source: committed descriptor failed validation');
    }
  } catch (error) {
    logger.warn(
      { backendId, reason: error instanceof Error ? error.message : 'read_failed' },
      'File descriptor source: could not read committed descriptor',
    );
  }

  return {
    getDescriptor: (requestedBackendId) =>
      wrapper !== undefined && requestedBackendId === wrapper.descriptor.backendId ? wrapper : undefined,
  };
}
